default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch('TW_IN_OUT_DB_USERNAME', 'postgres') %>
  password:
  host: <%= ENV.fetch('TW_IN_OUT_DB_HOST', 'localhost') %>

development:
  <<: *default
  database: tw_in_out_development

test:
  <<: *default
  database: tw_in_out_test

production:
  adapter: postgresql
  database: tw_in_out_production
  pool: 5
  timeout: 5000
